// ARCHIVE/backend-logic/project-templates/finance-nextjs-template/components/FinanceCard.tsx
import React from 'react';

interface FinanceCardProps {
  title?: string;
}

export const FinanceCard: React.FC<FinanceCardProps> = ({ 
  title = 'FinanceCard for finance' 
}) => {
  return (
    <div className="financecard-component">
      <h2>{title}</h2>
      <p>This is a finance-specific FinanceCard component powered by backend logic.</p>
    </div>
  );
};

export default FinanceCard;

// INTELLIGENCE/backend-logic/project-templates/finance-vue-template/components/FinanceCard.vue
<template>
  <div class="financecard-component">
    <h2>FinanceCard for finance</h2>
    <p>This is a finance-specific FinanceCard component powered by backend logic.</p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'FinanceCard',
  setup() {
    return {}
  }
})
</script>

<style scoped>
.financecard-component {
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 8px;
  background: #f9f9f9;
}
</style>
