// ARCHIVE/backend-logic/project-templates/vue-template/components/SampleComponent.vue
<template>
  <div class="sample-component">
    <h2>Sample Component</h2>
    <p>This is a sample Vue component powered by backend logic.</p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'SampleComponent',
  setup() {
    return {}
  }
})
</script>

<style scoped>
.sample-component {
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 8px;
}
</style>

// INTELLIGENCE/backend-logic/project-templates/react-template/components/SampleComponent.tsx
import React from 'react';

interface SampleComponentProps {
  title?: string;
}

export const SampleComponent: React.FC<SampleComponentProps> = ({ title = 'Sample Component' }) => {
  return (
    <div className="sample-component">
      <h2>{title}</h2>
      <p>This is a sample React component powered by backend logic.</p>
    </div>
  );
};

export default SampleComponent;
