// ARCHIVE/backend-logic/project-templates/finance-vue-template/components/FinanceDashboard.vue
<template>
  <div class="financedashboard-component">
    <h2>FinanceDashboard for finance</h2>
    <p>This is a finance-specific FinanceDashboard component powered by backend logic.</p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'FinanceDashboard',
  setup() {
    return {}
  }
})
</script>

<style scoped>
.financedashboard-component {
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 8px;
  background: #f9f9f9;
}
</style>

// ARCHIVE/backend-logic/project-templates/finance-nextjs-template/components/FinanceDashboard.tsx
import React from 'react';

interface FinanceDashboardProps {
  title?: string;
}

export const FinanceDashboard: React.FC<FinanceDashboardProps> = ({ 
  title = 'FinanceDashboard for finance' 
}) => {
  return (
    <div className="financedashboard-component">
      <h2>{title}</h2>
      <p>This is a finance-specific FinanceDashboard component powered by backend logic.</p>
    </div>
  );
};

export default FinanceDashboard;
